project:
  type: website

website:
  title: "Cultural Institutions"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
#      - text: "Projects"
#        menu:
#          - text: "Data Centers, Fortune 500s, and Power Plants"
#            href: analysis.qmd
#          - text: "Theaters, Operas, Colleges, and Auto Factories"
#            href: ml_models.qmd
#          - text: "---" # Adds a visual divider line
#          - text: "Museums"
#            href: https://example.com
#          - text: "Satellite Indicators"
#            href: https://example.com
#          - text: "Emily App(s)"
#            href: https://example.com
      - text: "Data"
        file: data.qmd
      - text: "Project Members"
        file: aboutus.qmd
        
      
        