---
title: "Scraping Census data"
format: pdf
editor: visual
---

```{r}
library(tidyverse) 
library(tidycensus)
library(httr2)
library(janitor)
library(maps)
library(stringr)
```

```{r}
my_key <- readLines("census_api_key.txt")
```

```{r}
year <- 2024

data_req <- request("https://api.census.gov/data") %>% 
  req_url_path_append(year) %>% 
  req_url_path_append("acs") %>% 
  req_url_path_append("acs5") %>% 
  req_url_query(get = c("NAME",
                        ))

```







```{r}
# Preallocate a list of tibbles
tbl_list <- vector(mode = "list", length = 2024-2009)

for(i in 2009:2024){
  year <- 2024
  
  data_req <- request("https://api.census.gov/data") %>% 
  req_url_path_append(year) %>% 
  req_url_path_append("acs") %>% 
  req_url_path_append("acs5") %>%
  req_url_query(get = c("NAME",
                        "B19326_001E", # Median pop
                        "B01003_001E", # TOTAL POPULATION
                        "B02001_002E" # White alone
                      #  "B15003_001"  # Total Pop 25 and older
                        ),
                `for` = I("county:*"),
                `in` = I("state:27"), #MN is 27 FIPS
                key = my_key,
                .multi = "comma")
  
  data_response <- req_perform(data_req)
  
  data_tbl <- data_response %>% 
    resp_body_json(simplifyVector = TRUE) %>% 
    janitor::row_to_names(1) %>% 
    as_tibble() %>% 
    mutate(across(c(2:4), as.integer)) %>% 
    mutate(perc_white = B02001_002E/B01003_001E) %>% 
    select(-c(state, county)) %>% 
    rename(county = NAME)
    

  colnames(data_tbl)[2] <- "med_income"
  colnames(data_tbl)[3] <- "total_pop"
  colnames(data_tbl)[4] <- "white_pop"
  colnames(data_tbl)[5] <- "perc_white"
  
  tbl_list[[i-2008]] <- data_tbl %>% 
    mutate(year = i)
}
```

```{r}
census_data <- tbl_list[[1]]

for(i in 2:16){ #instead of 2010:2024
  census_data <- census_data %>% 
    rbind(tbl_list[[i]])
}
```

```{r}
# fixing the text for counties
census_data <- census_data %>% 
  mutate(county = str_remove(county, "^* County, Minnesota"))
```

```{r}
library(readr)
write_csv(census_data, "census_scraped.csv")

```
