---
title: "historic_districts_exploration"
format: html
editor: visual
---

```{r}
# Load packages
library(tidyverse)
library(tidygeocoder)
library(janitor)
library(tidytext)
library(leaflet)
library(tigris)
library(readr)
```

```{r}
# Cleaning the historic_districts dataset so only the columns we want are present (add later)
```

--

```{r}
# Import cleaned (sort of) dataset
historic_districts <- read_csv("../data/Historic Districts/historic_districts_clean3_specific_addresses.csv")

# Mapping w/ leaflet!
prelim_map <- leaflet(data = historic_districts) %>%
   addTiles() %>%
   #addProviderTiles("Stadia.StamenWatercolor") %>% 
   addCircleMarkers(~longitude, ~latitude, popup = ~property_name, radius = 3)
prelim_map
```

```{r}
# Import (mostly) cleaned dataset
historic_districts <- read_csv("../data/Historic Districts/historic_districts_clean4.csv")

# Mapping w/ leaflet!
prelim_map <- leaflet(data = historic_districts) %>%
   addTiles() %>%
   #addProviderTiles("Stadia.StamenWatercolor") %>% 
   addCircleMarkers(~longitude, ~latitude, popup = ~property_name, radius = 3)
prelim_map
```

```{r}

# Mapping w/ leaflet!
prelim_map2 <- leaflet(data = historic_districts) %>%
   addTiles() %>%
   addMarkers(clusterOptions = markerClusterOptions(), popup = ~property_name)
  #addCircleMarkers(~longitude, ~latitude, popup = ~property_name, radius = 3)
prelim_map2
```

## Choropleths!!!

```{r}
# Group by state for data from historic_districts

by_state <- historic_districts %>% 
  group_by(state) %>% 
  summarise(total_acreage = sum(acreage_of_property, na.rm=TRUE),
            total_num_districts = n())

```
```{r}
by_state <- historic_districts %>% 
  group_by(state) %>% 
  summarise(total_acreage = sum(acreage_of_property, na.rm=TRUE),
            total_num_districts = n(),
            across(25:last_col(), \(x) sum(x, na.rm = TRUE)))
```


```{r}
areas <- read_csv("../data/Historic Districts/us_areas_cleaned.csv")
```
cb = TRUE simplfies the file, resolution = 20m is the lowest, this gives 2024 data
```{r}
# Get state geometries
states_sf <- tigris::states(cb = TRUE, resolution = "20m")
```

```{r}
# Join data to shapefile
map_data <- states_sf %>% 
  left_join(by_state, by = c("NAME" = "state")) %>% 
  left_join(areas, by = c("NAME" = "state_or_territory")) %>% 
  mutate(total_acreage_hd = total_acreage) %>% 
  select(-total_acreage)
```
```{r}
# Standardizing
# historic district acreage by total state land acreage
map_data <- map_data %>% 
  mutate(standardized_hd_acreage = total_acreage_hd/land_area_acres) 
```


## Standardized historic district area by state

```{r}
# Create a color palette for the map
# might want to change this to binning or quantile or something

my_palette <- colorNumeric(
  palette = "viridis", 
  domain = map_data$standardized_hd_acreage,
  na.color = "transparent"
)
```

```{r}
leaflet(map_data) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(
    fillColor = ~my_palette(standardized_hd_acreage),
    fillOpacity = .75,
    color = "white", # border color
    weight = 1,
    smoothFactor = 0.5, # slightly crisper borders -- default is 1 (higher values > more simplification > jaggier borders but shorter rendering)
    # add the highlight/hover and tooltip things
  ) %>% 
  addLegend(
    pal = my_palette,
    value = map_data$standardized_hd_acreage, # same as values   = ~total_num_districts
    position = "bottomright",
    title = "Hist. Dist. area/state land area"
  )
```






## Land area by state
Chloropleth map for \# of acres of districts
# MAYBE SHOULD JOIN DATA FOR THE TOTAL ACREAGE OF THE WHOLE STATE TO STANDARDIZE 
# ^ for this should find the area of each state and then divide the acreage by that...


```{r}
# Create a color palette for the map
# might want to change this to binning or quantile or something

my_palette <- colorNumeric(
  palette = "viridis", 
  domain = map_data$land_area_acres,
  na.color = "transparent"
)
```

```{r}
leaflet(map_data) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(
    fillColor = ~my_palette(land_area_acres),
    fillOpacity = .75,
    color = "white", # border color
    weight = 1,
    smoothFactor = 0.5, # slightly crisper borders -- default is 1 (higher values > more simplification > jaggier borders but shorter rendering)
    # add the highlight/hover and tooltip things
  ) %>% 
  addLegend(
    pal = my_palette,
    value = map_data$land_area_acres, # same as values   = ~total_num_districts
    position = "bottomright",
    title = "land area by state"
  )
```




```{r}
# 
# acreage_of_property na.rm = TRUE --> ignore missing values

```



```{r}
# choosing the var

#explore_var <- map_data$total_num_districts
```



```{r}
# Create a color palette for the map
# might want to change this to binning or quantile or something

my_palette <- colorNumeric(
  palette = "viridis", 
  domain = map_data$total_num_districts,
  na.color = "transparent"
)
```

```{r}
leaflet(map_data) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(
    fillColor = ~my_palette(total_num_districts),
    fillOpacity = .75,
    color = "white", # border color
    weight = 1,
    smoothFactor = 0.5, # slightly crisper borders -- default is 1 (higher values > more simplification > jaggier borders but shorter rendering)
    # add the highlight/hover and tooltip things
  ) %>% 
  addLegend(
    pal = my_palette,
    value = map_data$total_num_districts, # same as values   = ~total_num_districts
    position = "bottomright",
    title = "# of historic districts"
  )
```

```{r}
# Create a color palette for the map
# might want to change this to binning or quantile or something

my_palette <- colorNumeric(
  palette = "viridis", 
  domain = map_data$total_acreage_hd,
  na.color = "transparent"
)
```

```{r}
leaflet(map_data) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(
    fillColor = ~my_palette(total_acreage_hd),
    fillOpacity = .75,
    color = "white", # border color
    weight = 1,
    smoothFactor = 0.5, # slightly crisper borders -- default is 1 (higher values > more simplification > jaggier borders but shorter rendering)
    # add the highlight/hover and tooltip things
  ) %>% 
  addLegend(
    pal = my_palette,
    value = map_data$total_acreage_hd, # same as values   = ~total_num_districts
    position = "bottomright",
    title = "acreage of historic districts"
  )
```
