---
title: "historic districts cleaning version 2 part 2"
format: html
editor: visual
---

```{r}
# Packages
library(tidyverse)
```

```{r}
# Importing pre-cleaned data
historic_districts <- read_csv("../data/Historic Districts/historic_districts_clean3_specific_addresses.csv")
```
```{r}
# Removing unnecessary columns
# And making the address more human-readable
historic_districts <- historic_districts %>% 
  select(-nhl_designated_date, # 99% NA
         -prefix, # 85% NA
         -park_name, # 98% NA
         -level_of_significance_international # they were all false
         ) %>% 
  mutate(address = paste(property_name, city, state, sep = ", "))
```

## Widening

```{r}
# Split into binary (0 for false 1 for true) for the areas of significance
historic_districts <- historic_districts %>% 
  mutate(aos = area_of_significance) 

library(fastDummies)
widened_historic_districts <- dummy_cols(
    historic_districts,
    select_columns = "aos",
    split = "; "
  )
```

```{r}
widened_historic_districts <- widened_historic_districts %>% 
  clean_names() %>% 
  select(-aos)
```


## Fixing the duplicates
listed_date max
Lore Historic District = Lore, Seth And Irwinton Historic District (Boundary Increase)
Additional Documentation
li, lii
 parentheses
 match state, county, city
 
```{r}
historic_districts_parentheses <- widened_historic_districts %>% 
  filter(str_detect(property_name, "\\(Boundary") | str_detect(property_name, "\\(Additional")) %>% 
  mutate(cleaned_name = str_remove(property_name, " \\(.*")) %>% 
  distinct(cleaned_name)
```
```{r}
widened_historic_districts_nodupes <- widened_historic_districts

for(i in 1:nrow(historic_districts_parentheses)){
  
  all_group <- widened_historic_districts %>% 
      filter(str_detect(property_name, historic_districts_parentheses[[i, "cleaned_name"]]))
  
  most_recent <- all_group %>% 
    slice_max(listed_date, n=1)
  
  to_drop <- anti_join(all_group, most_recent, by = "property_name")
  
  widened_historic_districts_nodupes <- anti_join(
    widened_historic_districts_nodupes, 
    to_drop, 
    by = "property_name") 
}
```


```{r}
widened_historic_districts_nodupes <- widened_historic_districts

for(i in 1:nrow(historic_districts_parentheses)){
  
  #current_state <- historic_districts_parentheses$state[i]
  #current_county <- historic_districts_parentheses$county[i]
  #current_city <- historic_districts_parentheses$city[i]
  
  temp_name_group <- widened_historic_districts %>% 
      filter(str_detect(property_name, historic_districts_parentheses[[i, "cleaned_name"]])
               #state == current_state,
               #county == current_county,
               #city ==  current_city
             ) %>% # ensuring that it's acc the same place
      select(-slice_max(listed_date)) # getting the most recent one
  
  widened_historic_districts_nodupes <- anti_join(widened_historic_districts_nodupes, 
                                                  temp_name_group, 
                                                  by = "property_name") 
}

```




```{r}
temptemp <- widened_historic_districts %>% 
  select(ref_number, property_id)


  
  df_clean <- df %>% distinct(column_name, .keep_all = TRUE)
  anyDuplicated(temptemp$property_id) # is not 0...
  anyDuplicated(temptemp$ref_number) # is also not 0 but more than the above...
```


## Fixing the NA locations
```{r}
# Getting the simpler addresses + renaming these cols
```

```{r}

```


