---
title: "historic districts cleaning version 2"
format: html
editor: visual
---

```{r}
# Load packages
library(tidyverse)
library(tidygeocoder)
library(janitor)
library(tidytext)
library(leaflet)
library(lubridate)
library(arcgisgeocode)
```

## Historic Districts

```{r}
#\| eval: false
# Loading historic landmarks data for historic districts!
historic_landmarks <- read_csv("../data/Historic Districts/Raw/csv_RAW_national-register-listed_20260522.csv") # .. means one folder up
```

```{r}
#\| eval: false
# Filtering the historic landmarks dataset to make sure that only historic districts are present
historic_districts <- historic_landmarks %>% 
  clean_names() %>% 
  mutate(listed_date = mdy(listed_date),
         nhl_designated_date = mdy(nhl_designated_date),
         across(where(is.character) & -c(prefix, street_number, external_link, other_names), str_to_title),
         district_name = property_name) %>%
  filter(str_detect(district_name, "Historic District")) %>% 
  mutate(district_name = str_remove(district_name, " Historic District")) %>% 
  mutate(address = paste(property_name, street_number, city, state, sep=", "))
```

```{r}
#\| eval: false
#splitting addresses into groups of 100 for easier geocoding
groups <- split(historic_districts, ceiling(seq_len(nrow(historic_districts)) / 100))

geocoded_groups <- map(groups,~ geocode(.x, address = address, method = "arcgis", lat = latitude, long = longitude))
```

```{r}
#\| eval: false
new_tibble <- geocoded_groups[[1]]
for(i in 2:length(geocoded_groups)){
  new_tibble <- bind_rows(new_tibble, geocoded_groups[[i]])
}
```

```{r}
#\| eval: false
#write_csv(new_tibble, "historic_districts_clean3_specific_addresses.csv")
```

## Scraping Census Area Data

```{r}
library(robotstxt)
library(rvest)
library(janitor)
```


```{r}
paths_allowed("https://www.census.gov/") # came back true so we can scrape yay
```
```{r}
page <- read_html("https://www.census.gov/geographies/reference-files/2010/geo/state-area.html")
table <- page %>% html_elements("table")
areas_raw <- html_table(table[[1]])
```

```{r}
# Don't really care about the different types of water area, so I will delete those columns
areas_cleaned <- areas_raw[,1:7]
```
```{r}
# Fixing column names
new_names <- paste(colnames(areas_cleaned), areas_cleaned[2,], sep = "_")
colnames(areas_cleaned) <- str_remove_all(new_names, "[0-9]") # using regex to remove the #s
areas_cleaned <- areas_cleaned %>% 
  clean_names() %>% 
  slice(-(1:2)) # removing the 'header' rows

colnames(areas_cleaned)[1] <- "state_or_territory"
```
```{r}
# Fixing rows -- Removing the random blank rows and also the "island areas:" etc
areas_cleaned <- areas_cleaned %>% 
  mutate(state_or_territory = str_remove_all(state_or_territory, "[0-9]")) %>% 
  filter(!if_all(everything(), ~.x=="")) %>% 
  slice(-55) %>% #removing the row that said "Islands:"
  slice(-2) #removing the US row since it isn't clear/there is already a total
```
```{r}
# Making the cols the right types
areas_cleaned <- areas_cleaned %>% 
  mutate(across(c(2:ncol(areas_cleaned)), parse_number)) %>%  # to remove commas
  mutate(across(c(2:ncol(areas_cleaned)), as.numeric))
```

```{r}
# Getting it in acres (since the other dataset is in acres)
# 1 square mile is 640 acres
areas_cleaned <- areas_cleaned %>% 
  mutate(
    total_area_acres = total_area_sq_mi * 640,
    land_area_acres = land_area_sq_mi * 640,
    water_area_acres = water_area_sq_mi * 640
  )
```

```{r}
write_csv(areas_cleaned, "us_areas_cleaned.csv")
```
