---
title: "colleges_data_cleaning"
format: html
---

```{r}
library(tidyverse)
library(rvest)
library(dplyr)
```

```{r}
#checking permission to scrape
library(robotstxt)
paths_allowed("https://sites.ed.gov/whhbcu/one-hundred-and-five-historically-black-colleges-and-universities/")
```

```{r}
hbcu_page <- read_html("https://sites.ed.gov/whhbcu/one-hundred-and-five-historically-black-colleges-and-universities/")
hbcu_page
```

```{r}
#parsing HTML table into data frame
hbcu_table <- hbcu_page %>%
  html_element("table") %>%
  html_table(header = TRUE)
```

```{r}
#reading in and cleaning LACs csv
lacs <- read_csv("../data/Colleges/US-News-Rankings-LACs-Through-2026.csv")
```


```{r}
#reading in postsecondary schools locations
postsecondary_school_locations <- read_csv("../data/Colleges/Postsecondary_School_Locations_2023-24.csv")
```


```{r}
#joining LACs and location datasets
lacs_locations <- lacs %>%
  left_join(
    postsecondary_school_locations %>%
      select(UNITID, LAT, LON, CITY, ZIP),
      by = c("IPEDS ID" = "UNITID")
  )
```


```{r}
#duplication conflict when trying to join the hbcu and location datasets
hbcu_table[55,]
postsecondary_school_locations[375,]

hbcu_table %>%
  count(Name) %>%
  filter(n > 1)

postsecondary_school_locations %>%
  count(NAME) %>%
  filter(n > 1)
```

```{r}
#resolved conflict by making college names distinct
distinct_locations <- postsecondary_school_locations %>%
  distinct(NAME, .keep_all = TRUE)

hbcus_locations <- hbcu_table %>%
  left_join(distinct_locations %>%
      select(NAME, LAT, LON), by = c("Name" = "NAME")
      )
```

```{r}
# adding state column to HBCU dataset
hbcus_locations <- hbcus_locations %>%
  mutate(State = str_extract(
    Address, paste(state.name, collapse = "|")), 
    .after = Address
  )
```

```{r}
# writing csvs for completed, cleaned datasets 
write_csv(lacs_locations, "LACs_coordinates.csv")
write_csv(hbcus_locations, "HBCUs_coordinates.csv")
```

```{r}
# creating a joined csv
lacs_locations <- lacs_locations %>%
  mutate(college_type = "LAC")

hbcus_locations <- hbcus_locations %>%
  mutate(college_type = "HBCU")

lacs_clean <- lacs_locations %>%
  rename(
    College = `College Name`,
    City = CITY,
    Latitude = LAT,
    Longitude = LON
  ) %>%
  mutate(college_type = "LAC")

hbcus_clean <- hbcus_locations %>%
  rename(
    College = Name,
    Latitude = LAT,
    Longitude = LON
  ) %>%
  mutate(college_type = "HBCU")

# combine into one dataset
joined_colleges <- bind_rows(lacs_clean, hbcus_clean)
```

```{r}
write_csv(joined_colleges, "joined_colleges.csv")
```
