---
title: "blog_post_charts"
format: html
---
# Replicating box plots from app for blog post visuals

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(scales)
library(patchwork)
```

```{r}
# Load IPUMS data
IPUMS_data <- read_csv("data/nhgis0002_ds272_20245_county.csv") %>%
  rename(
    total_population = AUO6E001, race_total = AUO7E001, white = AUO7E002,
    black = AUO7E003, american_indian_alaska_native = AUO7E004,
    asian = AUO7E005, native_hawaiian_pacific_islander = AUO7E006,
    other_race = AUO7E007, two_or_more_races = AUO7E008,
    education_total_25plus = AUQ8E001, bachelors_degree = AUQ8E022,
    masters_degree = AUQ8E023, professional_degree = AUQ8E024,
    doctorate_degree = AUQ8E025, median_household_income = AURUE001
  ) %>%
  mutate(
    median_household_income = ifelse(median_household_income < 0, NA_real_,
                                      median_household_income),
    GEOID = str_pad(as.character(TL_GEO_ID), 5, pad = "0"),
    pct_black = 100 * black / race_total,
    pct_bachelors_plus = 100 * (bachelors_degree + masters_degree +
                                   professional_degree + doctorate_degree) /
                                 education_total_25plus
  )

counties_sf <- counties(cb = TRUE, resolution = "20m", year = 2024) %>%
  left_join(IPUMS_data, by = "GEOID") %>%
  filter(!is.na(total_population)) %>%
  filter(!STATEFP %in% c("60", "66", "69", "72", "78")) %>%
  st_transform(crs = 4326)
```


```{r}
# Load institution data
colleges <- read_csv("data/colleges_app_clean.csv")
auto_facilities <- read_csv("data/auto_facilities_app_clean.csv")
theaters <- read_csv("data/theaters_app_clean.csv")
opera <- read_csv("data/opera_app_clean.csv")

attach_county_data <- function(points_df) {
  pts_sf <- st_as_sf(points_df, coords = c("longitude", "latitude"),
                      crs = 4326, remove = FALSE)
  joined <- st_join(
    pts_sf,
    counties_sf %>% select(GEOID, pct_black, pct_bachelors_plus, median_household_income),
    join = st_within, left = TRUE
  )
  st_drop_geometry(joined)
}

colleges <- attach_county_data(colleges)
auto_facilities <- attach_county_data(auto_facilities)
theaters <- attach_county_data(theaters)
opera <- attach_county_data(opera)
```


```{r}
# Create function for chart template to be used across each institution
blog_boxplot <- function(df, group_col, value_col, colors, x_lab) {
  ggplot(df, aes(x = .data[[group_col]], y = .data[[value_col]],
                  fill = .data[[group_col]])) +
    geom_boxplot(outlier.alpha = 0.4, width = 0.55) +
    geom_jitter(width = 0.15, size = 1.6, alpha = 0.45, color = "black") +
    scale_fill_manual(values = colors, guide = "none") +
    coord_flip() +
    labs(x = NULL, y = x_lab) +
    theme_minimal(base_size = 15) +
    theme(panel.grid.minor = element_blank())
}
```

```{r}
# Colleges: % Black population by college type
#| fig-width: 8
#| fig-height: 4.5
blog_colleges <- colleges %>%
  filter(!is.na(pct_black)) %>%
  blog_boxplot(
    group_col = "type", value_col = "pct_black",
    colors = c("HBCU" = "#0072B2", "LAC" = "#E69F00"),
    x_lab = "Black or African American alone, % of county population"
  ) +
  scale_y_continuous(labels = label_number(suffix = "%")) +
  labs(
    title = "Percentage of Black Residents in Counties with LACs and HBCUs",
    subtitle = "Value = the county each college is located in"
  ) +
  theme_minimal()

blog_colleges
```

```{r}
# Automotive: median household income by facility type
#| fig-width: 8
#| fig-height: 4
blog_auto <- auto_facilities %>%
  filter(!is.na(median_household_income)) %>%
  blog_boxplot(
    group_col = "type", value_col = "median_household_income",
    colors = c("EV Facility" = "#0072B2",
               "Traditional/Other Facility" = "#E69F00"),
    x_lab = "Median household income ($, log scale)"
  ) +
  scale_y_log10(labels = label_dollar()) +
  labs(
    title = "Traditional and EV Facilities by Median Household Income",
    subtitle = "Value = the county each facility is located in"
  ) +
  theme_minimal()

blog_auto
```

```{r}
# Theaters/Opera data
theater_opera_combined <- bind_rows(
  theaters %>% mutate(institution_group = "Historic Theater"),
  opera %>% mutate(institution_group = "Opera Company")
) %>%
  select(institution_group, median_household_income, pct_bachelors_plus) %>%
  pivot_longer(
    cols = c(median_household_income, pct_bachelors_plus),
    names_to = "metric", values_to = "value"
  ) %>%
  filter(!is.na(value)) %>%
  mutate(metric = recode(metric,
                         median_household_income = "Median Household Income ($, log scale)",
                         pct_bachelors_plus = "Bachelor's Degree or Higher, 25+ (%)"
                         )
         )
```

```{r}
# Theaters/Opera: education and income charts
#| fig-width: 10
#| fig-height: 4.5
blog_income <- theater_opera_combined %>%
  filter(str_detect(metric, "Income")) %>%
  ggplot(aes(x = institution_group, y = value, fill = institution_group)) +
  geom_boxplot(outlier.alpha = 0.4, width = 0.55) +
  geom_jitter(width = 0.15, size = 1.4, alpha = 0.4, color = "black") +
  scale_fill_manual(
    values = c("Historic Theater" = "#0072B2", "Opera Company" = "#E69F00"),
    guide = "none"
  ) +
  scale_y_log10(labels = label_dollar(scale_cut = cut_short_scale())) +
  coord_flip() +
  labs(x = NULL, y = str_wrap("Median Household Income ($, log scale)", 30)) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    plot.margin = margin(r = 15)
  )

blog_education <- theater_opera_combined %>%
  filter(str_detect(metric, "Bachelor")) %>%
  ggplot(aes(x = institution_group, y = value, fill = institution_group)) +
  geom_boxplot(outlier.alpha = 0.4, width = 0.55) +
  geom_jitter(width = 0.15, size = 1.4, alpha = 0.4, color = "black") +
  scale_fill_manual(
    values = c("Historic Theater" = "#0072B2", "Opera Company" = "#E69F00"),
    guide = "none"
  ) +
  scale_y_continuous(labels = label_number(suffix = "%")) +
  coord_flip() +
  labs(x = NULL, y = str_wrap("Bachelor's Degree or Higher, 25+ (%)", 30)) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(l = 15)
  )

blog_final <- (p_income + p_education) +
  plot_layout(widths = c(1, 1)) +
  plot_annotation(
    title = "Historic Theaters and Operas Against Median Household Income and Education",
    subtitle = "Value = the county each institution is located in",
    theme_minimal()
  )

blog_final
```
